In [1]:
!pip install numpy


In [10]:
import numpy as np
arr = np.array([{1,2}, 2, 3, 4, 5])
print(arr)
print(type(arr), arr.shape)
print(arr[0])
arr[4] ={1,2,3}
print(arr)
print(type(arr[0]), type(arr[1]), type(arr[4]))

[{1, 2} 2 3 4 5]
<class 'numpy.ndarray'> (5,)
{1, 2}
[{1, 2} 2 3 4 {1, 2, 3}]
<class 'set'> <class 'int'> <class 'set'>


In [25]:
c = np.zeros((2,3))
print(c)
b =np.ones((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
a = np.full((3,4),88)
print(a)

[[88 88 88 88]
 [88 88 88 88]
 [88 88 88 88]]


In [36]:
f = np.arange(10, 1000, 100)
print(f)
g = np.linspace(0,10,num=5)
print(g)

[ 10 110 210 310 410 510 610 710 810 910]
[ 0.   2.5  5.   7.5 10. ]


In [39]:
a = np.array([1,2,4])
b = np.array([3,56,7])
r = np.vstack((a,b))
print(r)
z = np.hstack((a,b))
print(z)

[[ 1  2  4]
 [ 3 56  7]]
[ 1  2  4  3 56  7]


In [42]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2,:3]
print(b)
c = a[1:3]
print(c)

[[1 2 3]
 [5 6 7]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
array_1d = np.arange(1, 13)
print(array_1d)

array_3x4 = np.random.randint(10, 50, size=(3, 4))
print(array_3x4)

array_1d[array_1d % 2 == 0] = -1
print(array_1d)

array_3x4 = array_3x4 - 5
print(array_3x4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[31 20 26 31]
 [43 28 25 46]
 [26 35 28 14]]
[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1]
[[26 15 21 26]
 [38 23 20 41]
 [21 30 23  9]]


In [45]:
last_four = array_1d[-4:]
print(last_four)

slice_3x4 = array_3x4[:2, -2:]
print(slice_3x4)

array_1d[1:3] = 100
print(array_1d)

array_3x4[2, :] = 0
print(array_3x4)

[ 9 -1 11 -1]
[[21 26]
 [20 41]]
[  1 100 100  -1   5  -1   7  -1   9  -1  11  -1]
[[26 15 21 26]
 [38 23 20 41]
 [ 0  0  0  0]]


In [46]:
indexed_elements = np.array([array_3x4[0, 0], array_3x4[1, 1], array_3x4[2, 2]])
print(indexed_elements)

array_1d[array_1d > 6] = -array_1d[array_1d > 6]
print(array_1d)

odd_elements = array_3x4[array_3x4 % 2 != 0]
print(odd_elements)

[26 23  0]
[   1 -100 -100   -1    5   -1   -7   -1   -9   -1  -11   -1]
[15 21 23 41]


In [47]:
sorted_1d = np.sort(array_1d)
print(sorted_1d)

sorted_3x4 = np.sort(array_3x4, axis=0)[::-1]
print(sorted_3x4)

index_max_1d = np.argmax(array_1d)
print(index_max_1d)

index_min_3x4 = np.argmin(array_3x4)
print(index_min_3x4)

[-100 -100  -11   -9   -7   -1   -1   -1   -1   -1    1    5]
[[38 23 21 41]
 [26 15 20 26]
 [ 0  0  0  0]]
4
8


In [48]:
new_array_1d = np.random.randint(1, 100, size=12)
print(new_array_1d)

stacked_v = np.vstack((array_1d, new_array_1d))
print(stacked_v)

stacked_h = np.column_stack((array_3x4[:, 0], array_3x4[:, 2]))
print(stacked_h)

[88 29 64 88 25 32 21 96 49 57 97 26]
[[   1 -100 -100   -1    5   -1   -7   -1   -9   -1  -11   -1]
 [  88   29   64   88   25   32   21   96   49   57   97   26]]
[[26 21]
 [38 20]
 [ 0  0]]


In [49]:
indices_where_greater_5 = np.where(array_1d > 5)
array_1d[indices_where_greater_5] = 0
print(array_1d)

max_indices_3x4 = np.where(array_3x4 == np.max(array_3x4))
print(max_indices_3x4)

[   1 -100 -100   -1    5   -1   -7   -1   -9   -1  -11   -1]
(array([1]), array([3]))
