In [4]:
import numpy as np
import
x = np.array([1,3])
y = np.array([1.0,4.0])
z = np.array([1,2],dtype=np.float16)


print(z.dtype)
print(y.dtype)
print(x.dtype)


float16
float64
int64


In [9]:
import time

a = np.random.random(100000000)
start_time = time.time()
start_cpu = time.process_time()
x = np.sum(a)
end_time = time.time()
end_cpu = time.process_time()

print(f"Result: {x}")
print(f"Time taken: {end_time - start_time} seconds")
print(f"CPU Time taken: {end_cpu - start_cpu} seconds")

Result: 50005880.56514648
Time taken: 0.06847596168518066 seconds
CPU Time taken: 0.0690030780000015 seconds


In [13]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)

print(x+y)
print(np.add(x,y))
print(x/y)
print(np.divide(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.sqrt(x,y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [16]:
x = np.array([[1,2,3]])
y = np.array([[5,6, 4],[7,8, 6], [1,2,3]])

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))
print(x.dot(y))
print(np.dot(x,y))
print(x @ y)

219
219
[[22 28 25]]
[[22 28 25]]
[[22 28 25]]


In [17]:
m = np.array([[9,10]])
l = np.array([[1,2],[3,4]])
print(m, l)
print(np.dot(m,l))

[[ 9 10]] [[1 2]
 [3 4]]
[[39 58]]


In [18]:
x = np.array([[1,2],[4,5],[7,8]])
print(np.max(x))
print(np.max(x, axis=0))
print(np.max(x, axis=1))

8
[7 8]
[2 5 8]


In [21]:
x = np.array([[1,2],[4,5],[7,8]])
print(x)
print("transpose\n",x.T)

[[1 2]
 [4 5]
 [7 8]]
transpose
 [[1 4 7]
 [2 5 8]]


In [26]:
data =  np.array([1,2,4,5,7,8])
print(data.shape)
print(data)
data = data.reshape((2,3))
print(data.shape)
print(data)


(6,)
[1 2 4 5 7 8]
(2, 3)
[[1 2 4]
 [5 7 8]]


In [27]:
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])

print(a.shape)
print(b.shape)
print(a+b)

(3,)
(3, 1)
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [28]:
b = np.array([[4],[5],[6]])
c = np.array([[1,2],[3,4],[5,6]])
d = b+c
print(d)
print(b.shape)
print(c.shape)
print(d.shape)

[[ 5  6]
 [ 8  9]
 [11 12]]
(3, 1)
(3, 2)
(3, 2)


In [29]:
# Array Creation
a = np.arange(10, 16)
b = np.arange(0.1, 0.6, 0.1)
c = np.arange(1, 10, dtype=np.int32).reshape(3, 3)

print(a.dtype, b.dtype, c.dtype)
print(a.shape, b.shape, c.shape)

int64 float64 int32
(6,) (5,) (3, 3)


In [30]:
# Elementwise Operations
x = np.arange(1, 7).reshape(2, 3)
y = np.arange(7, 13).reshape(2, 3)

sum_op = x + y
sum_np = np.add(x, y)
diff_op = x - y
diff_np = np.subtract(x, y)
mul_op = x * y
mul_np = np.multiply(x, y)
div_op = x / y
div_np = np.divide(x, y)
sqrt_x = np.sqrt(x)

print(sum_op, sum_np)
print(diff_op, diff_np)
print(mul_op, mul_np)
print(div_op, div_np)
print(sqrt_x)

[[ 8 10 12]
 [14 16 18]] [[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]] [[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]] [[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]] [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [31]:
# Matrix and Vector Operations
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

inner_dot = v.dot(w)
inner_np = np.dot(v, w)

x_mat = np.array([[1, 2], [3, 4]])
y_mat = np.array([[5, 6], [7, 8]])

mat_vec = np.dot(x_mat, v[:2])
mat_mat = np.dot(x_mat, y_mat)

print(inner_dot, inner_np)
print(mat_vec)
print(mat_mat)

32 32
[ 5 11]
[[19 22]
 [43 50]]


In [32]:
# Aggregation Operations
a_agg = np.arange(1, 10).reshape(3, 3)

max_all = np.max(a_agg)
min_all = np.min(a_agg)
sum_all = np.sum(a_agg)
max_row = np.max(a_agg, axis=1)
max_col = np.max(a_agg, axis=0)

print(max_all, min_all, sum_all)
print(max_row, max_col)

9 1 45
[3 6 9] [7 8 9]


In [33]:
# Reshaping and Transposing
a_reshaped = np.arange(1, 5).reshape(2, 2)
transposed = a_reshaped.T

print(a_reshaped.shape, transposed.shape)


(2, 2) (2, 2)


In [34]:
# Squeezing and Reshaping
a_squeeze = np.arange(4).reshape(4, 1)
flattened = a_squeeze.reshape(-1)
squeezed = a_squeeze.squeeze()
column_vector = flattened.reshape(-1, 1)

print(flattened.shape, squeezed.shape, column_vector.shape)

(4,) (4,) (4, 1)


In [35]:
# Array Broadcasting
a_broadcast = np.array([[1], [2], [3]])
b_broadcast = np.array([[10, 20], [30, 40], [50, 60]])

broadcast_add = a_broadcast + b_broadcast

print(broadcast_add)

[[11 21]
 [32 42]
 [53 63]]
